(executable
 (name obj)
 (modules obj)
 (public_name mgit.obj)
 (package mgit)
 (libraries mgit))

(library
 (name test)
 (modules test)
 (libraries unix))

(test
 (name g)
 (modules g)
 (libraries mgit.unix test))

(cram
 (package mgit)
 (applies_to object)
 (deps %{bin:mgit.obj}))

(cram
 (package mgit)
 (applies_to bundle)
 (deps %{bin:mgit} trim.ml))

(cram
 (package mgit)
 (applies_to mem)
 (locks git-daemon)
 (deps %{bin:mgit} add.ml trim.ml))

(cram
 (package mgit)
 (applies_to pull)
 (locks git-daemon)
 (deps %{bin:mgit} trim.ml))

(cram
 (package mgit)
 (applies_to push)
 (locks git-daemon)
 (deps %{bin:mgit}))

(cram
 (package mgit)
 (applies_to shallow)
 (locks git-daemon)
 (deps %{bin:mgit} trim.ml))

(cram
 (package mgit)
 (applies_to full)
 (locks git-daemon)
 (deps %{bin:mgit} grep.ml))
